import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;


public class PSUtils {
	
	final static String SERVER_NAME = "AwesomeProxy";
	
	
	public static String getRFC1123Date() {
		return new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss z", Locale.US).format(new Date());
	}
	
	public static String getSimpleHtmlMessage(String title, String message) {
		
		return getSimpleHtml(title, "<p>" + message + "</p>");
	}
	
	public static String getSimpleHtml(String title, String content) {
		String body = "<!doctype html>\n<html>";
		body += "<head><title>" + title + "</title></head>";
		body += "<body>";
		body += "<header><h1>" + title + "</h1></header>";
		body += "<main>" + content + "</main>";
		body += "<footer><i>Message generated by <a href=\"/\">" + SERVER_NAME + "</a> at " + getRFC1123Date() + "</i></footer>";
		body += "</body>";
		body += "</html>";
		
		return body;
	}
}
