import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Locale;


public class Utils {
	
	final static String SERVER_NAME = "AwesomeProxy";
	
	final static String HTTP_VERSION = "HTTP/1.1";
	final static String CRLF = "\r\n";
	final static String LF = "\n";
	final static String HTTP_HEADER_END = CRLF + CRLF;
	
	/**
	 * Returns the current datetime as an RFC 1123 formatted string
	 */
	public static String getRFC1123Date() {
		return new SimpleDateFormat("EEE, dd MMM yyyy HH:mm:ss z", Locale.US).format(new Date());
	}
	
	public static String getSimpleHtmlMessage(String title, String message) {
		
		return getSimpleHtml(title, "<p>" + message + "</p>");
	}
	
	public static String getSimpleHtml(String title, String content) {
		String body = "<!doctype html>\n<html>";
		body += "<head><title>" + title + "</title></head>";
		body += "<body>";
		body += "<header><h1>" + title + "</h1></header>";
		body += "<main>" + content + "</main>";
		body += "<footer><i>Page generated by <a href=\"/\">" + SERVER_NAME + "</a> at " + getRFC1123Date() + "</i></footer>";
		body += "</body>";
		body += "</html>";
		
		return body;
	}
	
	/**
	 * Formats an HTTP header key-value pair
	 */
	public static String httpHeader(String key, String value) {
		return CRLF + key + ": " + value;
	}
}
